# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5c4fd02
_src_path: gh:scipp/copier_template
description: Neutron image tiff format and related python tools
max_python: '3.12'
min_python: '3.10'
namespace_package: ''
nightly_deps: ''
orgname: ''
prettyname: EssTiff
projectname: esstiff
related_projects: ''
year: 2025
